services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=aamv

    php:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: php8
        depends_on:
            - mysql
        volumes:
            - ./:/var/www/html/
            - ./docker/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini

    nginx:
        image: nginx
        container_name: nginx_php8
        depends_on:
            - php
            - mysql
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www/html/
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
