services:
    mysql:
        image: mysql:5.6
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=aamv

    php:
        image: mehrdadkhah/php7:alpine-7.1
        container_name: php7
        depends_on:
            - mysql
        volumes:
            - ./:/var/www/html/
            - ./docker-config/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini

    nginx:
        image: nginx
        container_name: nginx_php7
        depends_on:
            - php
            - mysql
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www/html/
            - ./docker-config/nginx.conf:/etc/nginx/conf.d/default.conf
