imports:
    - { resource: security.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }

framework:
    translator:      { fallbacks: ["fr"] }
    secret:          "%env(APP_SECRET)%"
    router:
        resource: "%kernel.project_dir%/app/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    default_locale:  "fr"
    trusted_hosts:   ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.project_dir%/var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    mailer:
        dsn: '%env(MAILER_DSN)%'

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        '%kernel.project_dir%/app/Resources/views': ~
        '%kernel.project_dir%/src/AppBundle/Resources/views': AppBundle
    form_themes:
        - "bootstrap_5_layout.html.twig"
        - "form_theme.html.twig"
    globals:
        toolRepository: "@AppBundle\\Repository\\ToolRepository"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%env(DATABASE_HOST)%"
        port:     "%env(DATABASE_PORT)%"
        dbname:   "%env(DATABASE_NAME)%"
        user:     "%env(DATABASE_USER)%"
        password: "%env(DATABASE_PASSWORD)%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            AppBundle:
                type: attribute
                dir: '%kernel.project_dir%/src/AppBundle/Entity'
                prefix: AppBundle\Entity
                alias: AppBundle
